packages:
  - apps/*
  - packages/*
  - tools/*
  - services/*
ignoredBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
catalog:
  '@eslint/js': ~9.26.0
  '@fastify/autoload': ~6.3.0
  '@fastify/cors': ~11.0.1
  '@hono/node-server': ~1.14.1
  '@hono/trpc-server': ~0.3.4
  '@hookform/resolvers': ~5.0.1
  '@lexical/react': ~0.31.0
  '@radix-ui/react-accordion': ~1.2.10
  '@radix-ui/react-alert-dialog': ~1.1.13
  '@radix-ui/react-aspect-ratio': ~1.1.6
  '@radix-ui/react-avatar': ~1.1.9
  '@radix-ui/react-checkbox': ~1.3.1
  '@radix-ui/react-collapsible': ~1.1.10
  '@radix-ui/react-context-menu': ~2.2.14
  '@radix-ui/react-dialog': ~1.1.13
  '@radix-ui/react-dropdown-menu': ~2.1.14
  '@radix-ui/react-hover-card': ~1.1.13
  '@radix-ui/react-icons': ~1.3.2
  '@radix-ui/react-label': ~2.1.6
  '@radix-ui/react-menubar': ~1.1.14
  '@radix-ui/react-navigation-menu': ~1.2.12
  '@radix-ui/react-popover': ~1.1.13
  '@radix-ui/react-progress': ~1.1.6
  '@radix-ui/react-radio-group': ~1.3.6
  '@radix-ui/react-scroll-area': ~1.2.8
  '@radix-ui/react-select': ~2.2.4
  '@radix-ui/react-separator': ~1.1.6
  '@radix-ui/react-slider': ~1.3.4
  '@radix-ui/react-slot': ~1.2.2
  '@radix-ui/react-switch': ~1.2.4
  '@radix-ui/react-tabs': ~1.1.11
  '@radix-ui/react-toast': ~1.2.13
  '@radix-ui/react-toggle': ~1.1.8
  '@radix-ui/react-toggle-group': ~1.1.9
  '@radix-ui/react-tooltip': ~1.2.6
  '@tailwindcss/postcss': ^4
  '@tailwindcss/vite': ~4.1.6
  '@types/eslint-config-prettier': ~6.11.3
  '@types/node': ~22.15.17
  '@types/pg': ~8.15.1
  '@types/react': ~19.1.3
  '@types/react-dom': ~19.1.3
  '@vitejs/plugin-react-swc': ~3.9.0
  axios: ~1.8.4
  better-auth: ~1.2.8
  class-variance-authority: ~0.7.1
  cmdk: ~1.1.1
  date-fns: ~4.1.0
  dotenv-cli: ~8.0.0
  drizzle-kit: ~0.31.1
  drizzle-orm: ~0.43.1
  boring-avatars: ~1.11.2
  drizzle-valibot: ~0.4.1
  embla-carousel-react: ~8.6.0
  eslint: ~9.26.0
  eslint-config-prettier: ~10.1.5
  eslint-config-turbo: ~2.5.3
  eslint-plugin-import: ~2.31.0
  eslint-plugin-only-warn: ~1.1.0
  eslint-plugin-react: ~7.37.5
  eslint-plugin-react-hooks: ~5.2.0
  eslint-plugin-turbo: ~2.5.3
  fastify: ~5.3.3
  fastify-plugin: ~5.0.1
  globals: ~16.1.0
  hono: ~4.7.9
  input-otp: ~1.4.2
  lexical: ~0.31.0
  motion: ~12.12.1
  next-themes: ~0.4.6
  nuqs: ~2.4.3
  pg: ~8.15.6
  pino-pretty: ~13.0.0
  prettier: ~3.5.3
  radix-ui: ~1.4.1
  react: ~19.1.0
  react-day-picker: 8.10.1
  react-dom: ~19.1.0
  react-hook-form: ~7.56.4
  react-resizable-panels: ~3.0.2
  recharts: ~2.15.3
  redis: ~5.0.1
  shx: ~0.4.0
  sonner: ~2.0.3
  superjson: ~2.2.2
  tailwind-merge: ~3.2.0
  tailwindcss: ~4.1.6
  tailwindcss-animate: ~1.0.7
  tsup: ~8.4.0
  tsx: ~4.19.4
  turbo: ~2.5.3
  typescript: ~5.8.3
  typescript-eslint: ~8.32.0
  url-join: ~5.0.0
  valibot: ~1.1.0
  vaul: ~1.1.2
  vite: ~6.3.5
