import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@reloop/ui/components/sonner";
import { IconsSprite, ThemeProvider } from "@reloop/ui";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Reloop - Mailing Maid Easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NuqsAdapter>
          <ThemeProvider>
            {children}
            <Toaster />
            <IconsSprite />
          </ThemeProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
