import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@reloop/ui/components/sonner';
import { IconsSprite } from '@reloop/ui/components/icon';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Wrapper } from './Wrapper';

export const metadata: Metadata = {
  title: 'Reloop - Mailing Maid Easy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Wrapper>
          <NuqsAdapter>
            {children}
            <Toaster />
            <IconsSprite />
          </NuqsAdapter>
        </Wrapper>
      </body>
    </html>
  );
}
